spring:
  datasource:
    write:
      url: jdbc:h2:mem:write;DB_CLOSE_ON_EXIT=FALSE
      username: write
      password: write
    read:
      url: jdbc:h2:mem:read;DB_CLOSE_ON_EXIT=FALSE
      username: read
      password: read
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true